Failing suites in mocha tests now mark saucelabs job as failed
webdriverio/wdio-sauce-service pull request #20
Opened 2017-02-23 12:00 UTC by eelessam

This is to fix a problem that we had where tests that were failing were marked as passed in SauceLabs.

Given a test that looked like this:

describe('Login: Successful with a verfied user', () => {
	describe('Given I have something', () => {
		it('should be like that', () => {
		});
		describe('When I do something', () => {			
			it('should  be done', () => {
			});
		});
	});	
});

The first 'describe' line would be used as the title for the test in SauceLabs. This is treat as a suite by the sauce service.

The two 'it's' would be used as a test as they also contain an assertion. If the first 'it' passes but then the test fails in the next describe loop (due to an element not being found etc.), it never then reaches the 2nd 'it'. Which means on the terminal the test has failed but in SauceLabs its marked as passed.

I've added an afterSuite function to check to see if the suite contains an error then to mark the job as failed. Just as the functionality already exists for the type 'feature' in the same file.

2017-02-25 17:41 UTC, christian-bromann requested changes
@eelessam can you propose a reproducible example where I can examine the issue? Also does your fix work across all frameworks?

2017-03-16 09:53 UTC, eelessam commented
Hi @christian-bromann  I'll get this together for you in the next day or two

2017-04-26 07:57 UTC, christian-bromann commented
ping @eelessam

2017-04-26 09:13 UTC, eelessam commented
@christian-bromann 

Put together a quick example:
https://github.com/eelessam/WDIO-Sauce-Service-Example

If you run the test you'll see if fails but is marked as passed on Saucelabs.

Could you give me a heads up for the other frameworks it needs be working for and I will test. Is it Mocha, Cucumber and Jasmine?

2017-04-26 09:15 UTC, christian-bromann commented
> Is it Mocha, Cucumber and Jasmine?

Yes.

Can you clarify the issue. According to https://github.com/eelessam/WDIO-Sauce-Service-Example/blob/master/test/specs/google/failingGoogleTest.spec.js#L14 you actually do something that would let the test fail.

2017-04-26 09:28 UTC, eelessam commented
Yes, the issue is that as you can see I'm making the test fail but on the Saucelabs console the job for this test run is marked as passed.

This is because the sauce-service doesn't deal with or report on the fail that happens in the 'before'. The test obviously doesn't get to the 2nd 'it' so the sauce-service uses the result of the first 'it' as the result that it reports back to SauceLabs.

2017-04-26 09:35 UTC, christian-bromann approved these changes
Got it. My main concern was that we could count failures twice but this wouldn't make any difference. Thanks for explaining it again.

LGTM 👍

2017-04-26 09:35 UTC, merged

2017-04-26 10:06 UTC, christian-bromann commented
Published as `v0.4.0`